[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/servo/cross-aarch64-unknown-linux-gnu:main"
pre-build = ["apt update", "apt install -y libx11-dev"]

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/servo/cross-armv7-unknown-linux-gnueabihf:main"
pre-build = ["apt update", "apt install -y libx11-dev"]

[target.x86_64-unknown-linux-gnu]
image = "ubuntu:22.04"
pre-build = [
    "apt update",
    "apt install -y build-essential pkg-config m4 python3 python3-distutils llvm llvm-dev lld libclang-dev clang libx11-dev",
]
