[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/servo/cross-aarch64-unknown-linux-gnu:main"
pre-build = [
    "apt update",
    "apt install -y scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev",
    "apt install -y libasound2-dev libpulse-dev libfreetype6-dev libssl-dev libudev-dev libxrandr-dev",
]

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/servo/cross-armv7-unknown-linux-gnueabihf:main"
pre-build = ["apt update", "apt install -y libx11-dev"]
